# Generated by Django 5.1.2 on 2024-10-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0013_alter_fee_date_alter_fee_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='Fall 2024', max_length=20),
        ),
    ]
