# Generated by Django 5.1.2 on 2024-10-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0017_remove_student_department_remove_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='default_department', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='default_section', max_length=10),
        ),
    ]
