# Generated by Django 5.1.1 on 2024-10-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0019_admitcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmitCard',
        ),
    ]
