# Generated by Django 5.1.2 on 2024-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asms_app', '0016_student_sclass_alter_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.CharField(max_length=50),
        ),
    ]
